api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
        mime_types: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_enabled: false
        normalization_context:
            enable_max_depth: true
        # pagination_items_per_page: 30
        # pagination_client_enabled: true
        # pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            items_per_page_parameter_name: 'count'
    use_symfony_listeners: true
    eager_loading:
        max_joins: 50
