nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type']
        # max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            allow_credentials: true
            expose_headers: ['Content-Type']




# nelmio_cors:
#     defaults:
#         origin_regex: true
#         # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_origin: ['*'] 
#         # allow_origin: ['http://localhost:3000'] change in production
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         # '^/': null
#         '^/api/': ~
