security:
    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15    

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        registration:
            pattern: ^/api/users
            stateless: true
            methods: [POST]

        login:
            pattern: ^/api/login
            stateless: true

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATOR, ROLE_FAMILY_ADMIN, ROLE_USER]
        ROLE_ADMIN: [ROLE_FAMILY_ADMIN, ROLE_MODERATOR, ROLE_USER]
        ROLE_FAMILY_ADMIN: ROLE_USER
        ROLE_MODERATOR: ROLE_USER

    access_control:
        # Public endpoints
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, methods: [POST], roles: PUBLIC_ACCESS }
        - { path: ^/api/media_objects, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/check-email, roles: PUBLIC_ACCESS }
        - { path: ^/api/validate-invitation, roles: PUBLIC_ACCESS }
        - { path: ^/api/families/colors-used, roles: PUBLIC_ACCESS }
        - { path: ^/api/resend-verification-email, roles: PUBLIC_ACCESS }

        # Frontend access
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard/family-admin, roles: ROLE_FAMILY_ADMIN }
        - { path: ^/auth/settings, roles: ROLE_FAMILY_ADMIN }
        - { path: ^/dashboard, roles: ROLE_USER }

        # API endpoints
        - { path: ^/api/family-admin, roles: ROLE_FAMILY_ADMIN }
        - { path: ^/api, roles: ROLE_USER } # << This covers all other API endpoints
        - { path: ^/media_objects, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                App\Entity\User: 'auto'
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10