# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    frontend_url: '%env(FRONTEND_URL)%'
    mailer_from: '%env(MAILER_FROM)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\Events\:
        resource: '../src/Events'
        tags: ['kernel.event_subscriber']
    App\Events\JwtCreatedSubscriber:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: updateJwtData }
    App\Controller\EmailVerificationController: ~
    
    App\Security\CookieTokenExtractor:
        arguments:
            $cookieName: 'token'
        tags:
            - { name: 'lexik_jwt_authentication.token_extractor', priority: -10 }

    App\Controller\CreateMediaObjectActionController:
        tags: ['controller.service_arguments']

    App\Events\MediaObjectDeletionSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Events\PostCommentAuthorSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    App\Doctrine\Extension\PostCollectionExtension:
        tags:
            - { name: 'api_platform.doctrine.orm.query_extension.collection' }
    App\Service\FamilyInvitationMailer:
        arguments:
            $mailer: '@mailer.mailer'
            $twig: '@twig'
            $frontendUrl: '%env(FRONTEND_URL)%'
            $mailerFrom: '%env(MAILER_FROM)%'

    # App\Events\FamilyInvitationSubscriber:
    #     tags:
    #         - { name: doctrine.event_subscriber }

    # App\Events\PostSubscriber:
    #     tags:
    #         - { name: doctrine.event_subscriber }
    # App\DataPersister\PostDataPersister:
    #     tags:
    #         - { name: 'api_platform.state_processor', priority: 1, arguments: [ 'App\Entity\Post' ] }


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
